package pl.dawid.kaszyca.config;

public enum StatisticKeyEnum {
    CURRENT_LOGIN_USERS("CURRENT_LOGIN_USERS"),
    //USERS
    DAILY_AUCTION_VIEWS_BY_ID("DAILY_AUCTION_VIEWS_BY_ID"),
    DAILY_AUCTION_PHONE_CLICKS_BY_ID("DAILY_AUCTION_PHONE_CLICKS_BY_ID"),
    //ADMINS
    TOTAL_AUCTIONS("TOTAL_AUCTIONS"),
    TOTAL_USERS("TOTAL_USERS"),
    TOTAL_MESSAGES("TOTAL_MESSAGES"),
    TOTAL_ACTIVE_REPORTS("TOTAL_ACTIVE_REPORTS"),
    DAILY_NEW_AUCTIONS("DAILY_NEW_AUCTIONS"),
    DAILY_AUCTION_VIEWS("DAILY_AUCTION_VIEWS"),
    DAILY_AUCTION_PHONE_CLICKS("DAILY_AUCTION_PHONE_CLICKS"),
    DAILY_USERS_LOGIN("DAILY_USERS_LOGIN"),
    DAILY_REGISTRATIONS("DAILY_REGISTRATIONS"),
    DAILY_MESSAGES("DAILY_MESSAGES"),
    DAILY_REMOVED_AUCTIONS("DAILY_REMOVED_AUCTIONS"),
    DAILY_AUCTION_REPORTS("DAILY_AUCTION_REPORTS"),
    DAILY_EDITED_AUCTIONS("DAILY_EDITED_AUCTIONS");

    String value;

    StatisticKeyEnum(String type) {
        value = type;
    }
}
