package pl.dawid.kaszyca.config;

public enum StatisticKeyEnum {

    TOTAL_AUCTIONS("TOTAL_AUCTIONS"),
    TOTAL_USERS("TOTAL_USERS"),
    TOTAL_ACTIVE_REPORTS("TOTAL_ACTIVE_REPORTS"),
    TOTAL_MESSAGES("TOTAL_MESSAGES"),
    DAILY_NEW_AUCTIONS("DAILY_NEW_AUCTIONS"),
    DAILY_EDITED_AUCTIONS("DAILY_EDITED_AUCTIONS"),
    DAILY_AUCTION_VIEWS("DAILY_AUCTION_VIEWS"),
    DAILY_AUCTION_PHONE_CLICKS("DAILY_AUCTION_PHONE_CLICKS"),
    DAILY_AUCTION_REPORTS("DAILY_AUCTION_REPORTS"),
    DAILY_USERS_LOGIN("DAILY_USERS_LOGIN"),
    DAILY_REGISTRATIONS("DAILY_REGISTRATIONS"),
    DAILY_MESSAGES("DAILY_MESSAGES");

    String value;

    StatisticKeyEnum(String type) {
        value = type;
    }
}
